[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
depends = ['neocomplete.vim']
hook_source = '''
  autocmd FileType python setlocal omnifunc=jedi#completions
  autocmd FileType python setlocal completeopt-=preview
  let g:jedi#completions_enabled = 0
  let g:jedi#auto_vim_configuration = 0
  let g:jedi#show_call_signatures = 0
  let g:jedi#smart_auto_mappings = 0
  let g:neocomplete#force_omni_input_patterns.python = '\h\w*\|[^. \t]\.\w*'
'''

[[plugins]]
repo = 'ujihisa/neco-look'
on_ft = 'tex'

[[plugins]]
repo = 'Mizuchi/STL-Syntax'
on_ft = 'cpp'

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = 'cpp'
hook_source = '''
  "clang-vim c++11 
  let g:clang_exec = 'clang36'
  let g:clang_cpp_options = '-std=c++14 -stdlib=libc++'
  " disable auto completion for vim-clang
  let g:clang_auto = 0
  let g:clang_diagsopt = ''
  " default 'longest' can not work with neocomplete
  let g:clang_c_completeopt = 'menuone'
  let g:clang_cpp_completeopt = 'menuone'
'''
