[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/neocomplete.vim' 
if = "has('lua')"
hook_add = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/rc/neocomplete.rc.vim
'''

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_color_term = 239
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  "Tabline Statusline
  let g:lightline = {
        \ 'colorscheme': 'jellybeans'
        \ }
  
  let g:lightline.tab_component_function = {}
  let g:lightline.tab_component_function.suffix = 'MySuffix'
  function! MySuffix(n)
      return len(tabpagebuflist(a:n))
  endfunction
  
  let g:lightline.tab = {
              \ 'active': [ 'tabnum', 'filename', 'suffix', 'modified' ],
              \ 'inactive': [ 'tabnum', 'filename', 'suffix', 'modified' ] }
'''

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {}
  let g:quickrun_config.c = {'cmdopt':'-lm'}
'''

